#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "

#
# Create four Store Entities in various locations across Berlin
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
  	{
  		"id":"urn:ngsi-ld:Store:001","type":"Store",
  		"address":{"type":"PostalAddress","value":{"streetAddress":"Rue Abdelhafidh El Mekki 12 ","addressRegion":"Tunis","addressLocality":"La Marsa","postalCode":"2074"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.884096,10.2966678]}},
  		"name":{"type":"Text","value":"Monoprix LaMarsaPlage"}
  	},
  	{
  		"id":"urn:ngsi-ld:Store:002","type":"Store",
  		"address":{"type":"PostalAddress","value":{"streetAddress":"Av Habib Bourguiba 2","addressRegion":"Tunis","addressLocality":"La Marsa","postalCode":"2070"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.884031,10.2966612]}},
  		"name":{"type":"Text","value":"Monoprix LaMarsaZefir"}},
  	{
  		"id":"urn:ngsi-ld:Store:003","type":"Store",
  		"address":{"type":"PostalAddress","value":{"streetAddress":" 126 طريق حلق الوادي، الموقع الأثري بقرطاج ","addressRegion":"Tunis","addressLocality":"Friedrichshain","postalCode":"2032"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.8626736,10.3007877]}},
  		"name":{"type":"Text","value":"Monoprix Carthage Presidence"}
  	},
  	{
  		"id":"urn:ngsi-ld:Store:004","type":"Store",
  		"address":{"type":"PostalAddress","value":{"streetAddress":"Rue Bechir Khraief Kheireddine 1","addressRegion":"Tunis","addressLocality":"Le Kram","postalCode":"2037"}},
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.8322242,10.2661587]}},
  		"name":{"type":"Text","value":"MonoprixLeKram"}
  	}
  ]
}'


#
# Create a series of Shelf Entities and place the in each Store.
# Each shelf is designed to hold one product.
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
	{
  		"id":"urn:ngsi-ld:Shelf:unit001","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.884096,10.2966678]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Etagere D21"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit002","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.884096,10.2966678]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Etagere A12"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit003","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.884096,10.2966678]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Etagere Coin 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit004","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.884031,10.2966612]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Etagere Coin 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit005","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.884031,10.2966612]}},
  		"maxCapacity":{"type":"Integer","value":200},
  		"name":{"type":"Text","value":"Etagere Coin 2"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"}
  	},
  	{
  		"id":"urn:ngsi-ld:Shelf:unit006","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.8626736,10.3007877]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Etagere E3"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit007","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.8626736,10.3007877]},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Etagere E7"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit008","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.8626736,10.3007877]}},
  		"maxCapacity":{"type":"Integer","value":100},
  		"name":{"type":"Text","value":"Etagere F7"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit009","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.8626736,10.3007877]}},
  		"maxCapacity":{"type":"Integer","value":50},
  		"name":{"type":"Text","value":"Etagere G4"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"}
  	},
	{
  		"id":"urn:ngsi-ld:Shelf:unit010","type":"Shelf",
  		"location":{"type":"geo:json","value":{"type":"Point","coordinates":[36.8322242,10.2661587]}},
  		"maxCapacity":{"type":"Integer","value":200},
  		"name":{"type":"Text","value":"Etagere Coulloir 1"},
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:004"}
  	}
  ]
}'

#
# Create a series of Product Entities. 
# These are a series of alcoholc and non-alcoholic drinks which are available to sell.
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
    {
      "id":"urn:ngsi-ld:Product:001", "type":"Product",
      "name":{"type":"Text", "value":"Jus Orange"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:002", "type":"Product",
      "name":{"type":"Text", "value":"Jus Pomme"},
      "size":{"type":"Text", "value": "M"},
      "price":{"type":"Integer", "value": 1099}
    },
    {
      "id":"urn:ngsi-ld:Product:003", "type":"Product",
      "name":{"type":"Text", "value":"Bouteille Lait"},
      "size":{"type":"Text", "value": "M"},
      "price":{"type":"Integer", "value": 1499}
    },
    {
      "id":"urn:ngsi-ld:Product:004", "type":"Product",
      "name":{"type":"Text", "value":"Eau Minerale"},
      "size":{"type":"Text", "value": "XL"},
      "price":{"type":"Integer", "value": 5000}
    },
    {
      "id":"urn:ngsi-ld:Product:005", "type":"Product",
      "name":{"type":"Text", "value":"Eau Minerale"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:006", "type":"Product",
      "name":{"type":"Text", "value":"Jus Abricot"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:007", "type":"Product",
      "name":{"type":"Text", "value":"Eau Gazifié"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:008", "type":"Product",
      "name":{"type":"Text", "value":"Huile Mais"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    },
    {
      "id":"urn:ngsi-ld:Product:009", "type":"Product",
      "name":{"type":"Text", "value":"Huile Olive"},
      "size":{"type":"Text", "value": "S"},
      "price":{"type":"Integer", "value": 99}
    }
  ]
}'


#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:001
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:001","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit001"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:002","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit002"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:003"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:003","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:001"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit003"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:004"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	}
   
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:002
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:004","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit004"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":12}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:005","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:002"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit005"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:002"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":15}
  	}
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:003
# Note that Shelf Unit009 is currently unused
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:006","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit006"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:007","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit007"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:008"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	},
  	{
  		"id":"urn:ngsi-ld:InventoryItem:008","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:003"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit008"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:009"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'
#
# Create a series of InventoryItems Entities. 
# These the drinks on order in Store:004
#
curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -d '{
  "actionType":"APPEND",
  "entities":[
  	{
  		"id":"urn:ngsi-ld:InventoryItem:401","type":"InventoryItem",
  		"refStore":{"type":"Relationship","value":"urn:ngsi-ld:Store:004"},
  		"refShelf":{"type":"Relationship","value":"urn:ngsi-ld:Shelf:unit010"},
  		"refProduct":{"type":"Relationship","value":"urn:ngsi-ld:Product:001"},
  		"stockCount":{"type":"Integer","value":10000},
  		"shelfCount":{"type":"Integer","value":50}
  	}
   
  ]
}'

echo -e " \033[1;32mdone\033[0m"
